# -*- coding: utf-8 -*-
# vim: ft=yaml
---
stages:
  - test
  - lint
  - name: release
    if: branch = master AND type != pull_request

sudo: required
cache: bundler
language: ruby
dist: xenial

services:
  - docker

# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
env:
  matrix:
    - INSTANCE: debian-debian-9-develop-py3
    # - INSTANCE: ubuntu-ubuntu-1804-develop-py3
    # - INSTANCE: redhat-centos-7-develop-py3
    # - INSTANCE: redhat-fedora-29-develop-py3
    # - INSTANCE: suse-opensuse-leap-15-develop-py3
    # - INSTANCE: debian-debian-9-2019-2-py3
    - INSTANCE: ubuntu-ubuntu-1804-2019-2-py3
    - INSTANCE: redhat-centos-7-2019-2-py3
    # - INSTANCE: redhat-fedora-29-2019-2-py3
    # - INSTANCE: suse-opensuse-leap-15-2019-2-py3
    # - INSTANCE: debian-debian-9-2018-3-py2
    # - INSTANCE: ubuntu-ubuntu-1604-2018-3-py2
    # - INSTANCE: redhat-centos-7-2018-3-py2
    - INSTANCE: redhat-fedora-29-2018-3-py2
    - INSTANCE: suse-opensuse-leap-42-2018-3-py2
    # - INSTANCE: debian-debian-8-2017-7-py2
    # - INSTANCE: ubuntu-ubuntu-1604-2017-7-py2
    - INSTANCE: redhat-centos-6-2017-7-py2
    # - INSTANCE: redhat-fedora-28-2017-7-py2
    # - INSTANCE: suse-opensuse-leap-42-2017-7-py2

script:
  - bin/kitchen verify ${INSTANCE}

jobs:
  include:
    # Define the `lint` stage (runs `yamllint` and `commitlint`)
    - stage: lint
      language: node_js
      node_js: lts/*
      before_install: skip
      script:
        # Install and run `yamllint`
        - pip install --user yamllint
        # yamllint disable-line rule:line-length
        - yamllint -s . .yamllint pillar.example test/salt/pillar/debian.sls test/salt/pillar/ubuntu.sls test/salt/pillar/redhat.sls test/salt/pillar/suse.sls
        # Install and run `commitlint`
        - npm install @commitlint/config-conventional -D
        - npm install @commitlint/travis-cli -D
        - commitlint-travis
    # Define the release stage that runs `semantic-release`
    - stage: release
      language: node_js
      node_js: lts/*
      before_install: skip
      script:
        # Update `AUTHORS.md`
        - export MAINTAINER_TOKEN=${GH_TOKEN}
        - go get github.com/myii/maintainer
        - maintainer contributor

        # Install all dependencies required for `semantic-release`
        - npm install @semantic-release/changelog@3 -D
        - npm install @semantic-release/exec@3 -D
        - npm install @semantic-release/git@7 -D
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Run `semantic-release`
          - npx semantic-release@15
